"""Jinja2 templates for audit report rendering."""

from __future__ import annotations

from datetime import datetime, timezone

from jinja2 import Template

AUDIT_REPORT_TEMPLATE = Template("""# Audit Report

**Decision ID:** {{ decision_id }}
**Generated:** {{ generated_at }}

---

## Transaction Summary

| Field | Value |
|---|---|
| Decision ID | {{ decision_id }} |
| Decision Time | {{ decision_time }} |
| Outcome | {{ outcome }} |
| Confidence | {{ confidence }} |
| Calibrated Score | {{ "%.4f"|format(calibrated_score) }} |
| Raw Score | {{ "%.4f"|format(raw_score) }} |

## Narrative

{{ narrative }}

## Risk Drivers

{% for driver in top_drivers %}
{{ loop.index }}. {{ driver }}
{% endfor %}

## Similar Historical Cases

{% for case in nearest_cases %}
- {{ case }}
{% endfor %}
{% if not nearest_cases %}
- No similar cases available.
{% endif %}

## Counterfactual Analysis

{{ counterfactual or "Not available." }}

## Recommendation

{{ recommendation }}

## How to Replay This Decision

```
{{ replay_instructions }}
```

---

*This report was generated by Rift's automated audit system.*
*Report timestamp: {{ generated_at }}*
""")


def render_audit_report(report: dict) -> str:
    """Render an audit report using the Jinja2 template."""
    return AUDIT_REPORT_TEMPLATE.render(
        generated_at=datetime.now(timezone.utc).isoformat(),
        **report,
    )
